maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Installs and configures redmine as a Rails app"
version           "0.10.3"
recipe "redmine", "Installs and configures redmine"
